export const foodData = [
  {
    id: 1,
    restaurant: "Pizza Hut",
    distance: 1.4,
    rate: 4.4,
    name: "Pepperoni Pizza With Eggs",
    price: "4.50",
    image: "/img/pizza1.jpeg",
  },
  {
    id: 2,
    restaurant: "Curry Kingdom",
    distance: 2,
    rate: 4.8,
    name: "Chocolate Mousse Cake",
    price: "8.25",
    image: "/img/cake1.jpeg",
  },
  {
    id: 3,
    restaurant: "Pizza Hut",
    distance: 1.4,
    rate: 4.1,
    name: "Red Pepper and Cheese Pizza",
    price: "12.50",
    image: "/img/pizza2.jpeg",
  },
  {
    id: 4,
    restaurant: "Franktuary",
    distance: 2.1,
    rate: 4.3,
    name: "Cheeseburger",
    price: "9.00",
    image: "/img/burger1.jpeg",
  },
  {
    id: 5,
    restaurant: "Party Fowl",
    distance: 1.2,
    rate: 4.7,
    name: "Fish Salad Dish",
    price: "14.40",
    image: "/img/fish1.jpeg",
  },
  {
    id: 6,
    restaurant: "Yin and Yummy",
    distance: 2.4,
    rate: 4.5,
    name: "Tortilla Chips",
    price: "6.35",
    image: "/img/snack1.jpeg",
  },
  {
    id: 7,
    restaurant: "Party Fowl",
    distance: 1.2,
    rate: 4.7,
    name: "Salmon Dish with Vegetables",
    price: "9.50",
    image: "/img/fish2.jpeg",
  },
  {
    id: 8,
    restaurant: "Classico Italiano",
    distance: 1.9,
    rate: 4.9,
    name: "Pasta Dish",
    price: "11.00",
    image: "/img/salmon.jpeg",
  },
];
