import Head from "next/head";
import { HomeTop, MenuItems } from "../components";

export default function Home() {
  return (
    <>
      <Head>
        <title>Food Delivery App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* Home Top Component */}
      <HomeTop />

      {/* Menu Items */}
      <MenuItems />
    </>
  );
}
