import Head from "next/head";
import { HomeTop, MenuItems, Cart } from "../components";
import axios from "axios";

export default function Home({ foodList }) {
  return (
    <>
      <Head>
        <title>Daily Meal Food Delivery</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* Home Top Component */}
      <HomeTop />

      {/* Menu Items */}
      <MenuItems foodList={foodList} />

      {/* Cart */}
      <Cart />
    </>
  );
}

export const getServerSideProps = async () => {
  const { data } = await axios.get(`${process.env.NEXT_PUBLIC_HOST}/api/items`);
  return {
    props: {
      foodList: data,
    },
  };
};
